using CarAssignment.Application.Configuration;
using CarAssignment.Application.Services;
using CarAssignment.Core;
using CarAssignment.Core.Abstractions;
using CarAssignment.Core.Data;
using CarAssignment.Core.Data.Enums;
using CarAssignment.Core.Exceptions;
using Microsoft.Extensions.Options;
using Moq;

namespace CarAssignment.Tests;

/// <summary>
/// Generated by AI in order to handle Async EF Core methods in unit tests
/// </summary>
public class ParkingServiceTests : TestBase
{
    private readonly IOptions<ParkingConfiguration> _parkingConfiguration;

    private readonly IParkingService _parkingService;
    
    public ParkingServiceTests()
    {
        var carRepositoryMock = CreateRepositoryMock<Car>();
        var parkingSlotRepositoryMock = CreateRepositoryMock<ParkingSlot>();

        _parkingConfiguration = Options.Create(new ParkingConfiguration()
        {
            ParkingSlotCount = 5,
            PaymentIntervalInSeconds = 1
        });
        
        _parkingService = new ParkingService(carRepositoryMock.Object,
            parkingSlotRepositoryMock.Object,
            _parkingConfiguration);
    }
    
    [Fact]
    public async Task ThrowException_WhenAddingExistingCar()
    {
        SeedEntities(new Car
        {
            RegistrationNumber = "test",
            VehicleType = VehicleType.LARGE_CAR,
            ParkingEnterTime = DateTimeOffset.UtcNow
        });
        
        await Assert.ThrowsAsync<ConflictException>(() => 
            _parkingService.AllocateCarAsync("test", It.IsAny<VehicleType>()));
    }
    
    [Fact]
    public async Task ThrowException_WhenRemovingNonExistingCar()
    {
        SeedEntities(new Car
        {
            RegistrationNumber = "test",
            VehicleType = VehicleType.LARGE_CAR,
            ParkingEnterTime = DateTimeOffset.UtcNow
        });
        
        await Assert.ThrowsAsync<NotFoundException>(() => 
            _parkingService.DeallocateCarAsync("non-existing-test"));
    }
    
    [Fact]
    public async Task ThrowException_WhenNoAvailableSpace()
    {
        var entities = new List<Car>();
        for (var i = 0; i < _parkingConfiguration.Value.ParkingSlotCount; i++)
        {
            entities.Add(new Car
            {
                RegistrationNumber = $"test-{i}",
                VehicleType = VehicleType.LARGE_CAR,
                ParkingEnterTime = DateTimeOffset.UtcNow
            });
        }
        
        SeedEntities(entities.ToArray());
        
        await Assert.ThrowsAsync<NotAvailableSpaceException>(() => 
            _parkingService.AllocateCarAsync("test-9999", It.IsAny<VehicleType>()));
    }

    public override void Dispose()
    {
        ClearEntities<Car>();
        base.Dispose();
    }
}